[themes.default]
selector = { fg = "Black", bg = "LightCyan", add_modifier = "BOLD" }
node_title = { add_modifier = "BOLD" }

[char-sets.default]
selector_top = "▌"
selector_middle = "▌"
selector_bottom = "▌"
